services:
  backend:
    build: ./backend
    container_name: movie_booking_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: booking_backend.settings
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    container_name: movie_booking_redis
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    container_name: movie_booking_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
